### PR TITLE
Support manila in workstation

### PR DESCRIPTION
**Pull request by sjpb**
- Adds ceph client install to workstation ansible builds
- Adds `azimuth` user to desktop, used as guacamole user

### CODE REVIEW

**Review by JohnGarbutt — CHANGES_REQUESTED** [review]
OK, cool, we should get that tag sorted, but otherwise cool 👍

**Review by JohnGarbutt — APPROVED** [review]
Nice 👍

**Review by JohnGarbutt — APPROVED** [review]
Looks good to me, nice 👍

**Review by mkjpryor — APPROVED** [review]
LGTM

**Pull request merged**
